blog/urls.py
from django.urls import path
from . import views

urlpatterns = [   # IP주소/blog/
    path('', views.PostList.as_view()),  #인덱스부분 클래스로 대체
    path('<int:pk>/', views.PostDetail.as_view()),
    path('<int:pk>/new_comment/', views.new_comment),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('create_post/', views.PostCreate.as_view()),
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),
    path('category/<str:slug>/', views.category_page), # IP주소/blog/category/슬러그명/ 입력시 : views.py의 category_page()함수로
    path('tag/<str:slug>/', views.tag_page),   # IP주소/blog/tag/슬러그명/ 입력시 : views.py의 tag_page()함수 호출
    path('search/<str:q>/', views.PostSearch.as_view()),

    #path('', views.index),  # IP주소/blog
    #path('<int:pk>/', views.single_post_page)
]

myDjangoPrj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [ #IP주소/
    path('admin/', admin.site.urls),  # IP주소/admin이 온다면 url로 연결(admin.site.urls)
    path('blog/', include('blog.urls')), # IP주소/blog이 온다면 blog url로 연결
    path('', include('single_pages.urls')),   # IP주소/ admin,blog 제외한 모든것
    path('accounts/', include('allauth.urls'))  # 로그인 하는 url 연결
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
import os

# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):   #관리자페이지(admin)의 Tags목록에 이름을 보이게 하기
        return self.name

    def get_absolute_url(self): # IP주소/blog/tag/슬러그명/
        return f'/blog/tag/{self.slug}/'

class Category(models.Model):  # 카테고리 모델
    name = models.CharField(max_length=50, unique=True) # name 필드 : 각 카테고리의 이름, 동일한  name 불가
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)
    # SlugField : 사람이 읽을 수 있는 텍스트로 고유 URL생성, allow_unicode : SlugField의 한글지원

    def __str__(self):
        return self.name

    def get_absolute_url(self): #카테고리의 레코드별 URL 생성 규칙 정의
        return f'/blog/category/{self.slug}'
        # urls.py에서 상세페이지 url은 /blog/category/slug필드 로 정함 -> 그대로 url생성

    class Meta:  # Category의 메타 설정에서 복수형 이름 직접 지정 -> 관리자 페이지에 메뉴이름 Categories로
        verbose_name_plural = 'Categories'

class Post(models.Model):
    title = models.CharField(max_length=30) #CharField: 문자를 담는 필드(최대길이=30)
    hook_text = models.CharField(max_length=100, blank=True) # 데이터 자체가 변경됨->migration필수!
    content = models.TextField() # 문자열의 길이 제한X

    head_image = models.ImageField(upload_to='blog/images/%Y/%m/%d/', blank=True)
    # _media 생략됨 _media/blog/images/년/월/일 폴더에 저장됨
    # %Y 2022 / %y 22
    file_upload = models.FileField(upload_to='blog/files/%Y/%m/%d/', blank=True)
    created_at = models.DateTimeField() #DateTimeField: 월,일,시,분,초 기록할 수 있게 해주는 필드

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    #User 모델을 사용하여 author 작성(모델에서 외래키를 구현할때)
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    #Category 모델을 사용하여 category 작성
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)
    tags = models.ManyToManyField(Tag, blank=True)  # 다대다관계, null=True 필요X(자동으로 비움)

    def __str__(self):  #관리자페이지(admin)의 포스트 목록에 제목을 보이게 하기
        return f'[{self.pk}]{self.title}:: {self.author} : {self.created_at}'
        # self.pk : 해당 포스트의 pk값(각 레코드에 대한 고유값, 모델을 만들면 기본적으로 생성됨) , self.title : 해당 포스트의 제목
    def get_absolute_url(self): #포스트의 레코드별 URL 생성 규칙 정의
        return f'/blog/{self.pk}/' # urls.py에서 상세페이지 url은 /blog/레코드의pk/ 로 정함 -> 그대로 url생성

    def get_file_name(self):
        return os.path.basename(self.file_upload.name)

    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]
        # ~.txt ~~.docx 등을 가져옴 ->스플릿에 의해서 ~ txt / ~~ docx 두개로 쪼개서 배열스트링에 전달
        # a.b.c.txt -> a b c txt 로 쪼개지면 -> 배열에서 제일 마지막이 확장자임 (제일 마지막 원소 표시 : -1)

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        else:
            return 'https://dummyimage.com/50x50/ced4da/6c757d.jpg'

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE) # 포스트 지워지면 댓글도 같이 지워지도록
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.author} : {self.content}'

    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}'

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        else:
            return 'https://dummyimage.com/50x50/ced4da/6c757d.jpg'

blog/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

blog/views.py
from django.shortcuts import render, redirect

from .forms import CommentForm
from .models import Post, Category, Tag, Comment
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin   #author자동으로 넣기(+redirect)
from django.core.exceptions import PermissionDenied
from django.utils.text import slugify
from .forms import CommentForm
from django.shortcuts import get_object_or_404
from django.db.models import Q

# Create your views here.
class PostUpdate(LoginRequiredMixin,UpdateView):
    model = Post
    fields = ['title', 'hook_text', 'content', 'head_image', 'file_upload', 'category'] # , 'tags' 지움
    # 템플릿명: post_forms 자동 생성-> 겹치니까 다른 이름으로
    template_name = 'blog/post_update_form.html' #원래 제공하는 템플릿을 PostCreate가 사용해서 다른 템플릿 지정

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate,self).dispatch(request, *args, **kwargs)
        # 가입, 인증되었고 그 포스트의 작성자를 가져와서 현재 작성자와 같은지 확인
        else:
            raise PermissionDenied

    def form_valid(self, form):
        response = super(PostUpdate, self).form_valid(form)
        self.object.tags.clear()
        tags_str = self.request.POST.get('tags_str')
        if tags_str:  # 태그에 뭔가 있다면(NULL)이 아니라면
            tags_str = tags_str.strip()  # 문자열 앞뒤 빈칸 없앰
            tags_str = tags_str.replace(',',';')  # ,를 ;로 변경하고
            tags_list = tags_str.split(';')  # ; 단위로 쪼갬
            for t in tags_list:
                t = t.strip()
                tag, is_tag_created = Tag.objects.get_or_create(name=t)  # 기존의 태그라면 그 태그 사용, 아니라면 태그 생성
                if is_tag_created:  # 태그가 새로 만들어졌다면 (bool값이 true라면)
                    tag.slug = slugify(t, allow_unicode=True)
                    tag.save()
                self.object.tags.add(tag)
        return response

    def get_context_data(self, *, object_list=None, **kwargs):  #카테고리 카드를 채우기 위한 정보 정의
        context = super(PostUpdate,self).get_context_data()  # 기존에 제공했던 기능을 그대로 가져와 context에 저장
        if self.object.tags.exists():
            tags_str_list = list() #빈 리스트 생성
            for t in self.object.tags.all():
                tags_str_list.append(t.name) # tag의 name string 필드 가져와서 뒤에 넣기
            context['tags_str_default'] = ';'.join(tags_str_list)
        context['categories'] = Category.objects.all()  # 모든 카테고리를 가져와 'categories'라는 키에 연결해 담기
        context['no_category_post_count'] = Post.objects.filter(category=None).count
        #카테고리가 지정되지 않은 포스트의 개수를 세어, 'no_category_post_count'에 담기
        return context

class PostCreate(LoginRequiredMixin,UserPassesTestMixin,CreateView):  #사용자 입력
    model = Post
    fields = ['title', 'hook_text', 'content', 'head_image', 'file_upload', 'category']  # , 'tags' 지움
    # 템플릿명: post_forms 자동 생성
    def test_func(self):  #이미 등록된, 상속받은 함수
        return self.request.user.is_superuser or self.request.user.is_staff

    def form_valid(self, form):  #클래스 내의 함수-> 이벤트 발생 시 자동 실행
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_superuser or current_user.is_staff):
            # 가입,인증 되었고 슈퍼유저or 스텝유저 라면 현재 로그인된 유저로 자동 author
            form.instance.author = current_user
            response = super(PostCreate, self).form_valid(form)
            tags_str = self.request.POST.get('tags_str') #사용자가 작성한 정보 전달 방식(get,post)중 post (모델명이 아님)
            if tags_str:  #태그에 뭔가 있다면(NULL)이 아니라면
                tags_str = tags_str.strip() #문자열 앞뒤 빈칸 없앰
                tags_str = tags_str.replace(',', ';')  # ,를 ;로 변경하고
                tags_list = tags_str.split(';')  # ; 단위로 쪼갬
                for t in tags_list:
                    t = t.strip()
                    tag, is_tag_created = Tag.objects.get_or_create(name=t)  # 기존의 태그라면 그 태그 사용, 아니라면 태그 생성
                    if is_tag_created:  # 태그가 새로 만들어졌다면 (bool값이 true라면)
                        tag.slug = slugify(t, allow_unicode=True)
                        tag.save()
                    self.object.tags.add(tag)
            return response
        else:
            return redirect('/blog/') #올바른 유저가 아니라면 그냥 블로그 부름

    # 템플릿 : 모델명_form.html
    def get_context_data(self, *, object_list=None, **kwargs):  #카테고리 카드를 채우기 위한 정보 정의
        context = super(PostCreate,self).get_context_data()  # 기존에 제공했던 기능을 그대로 가져와 context에 저장
        context['categories'] = Category.objects.all()  # 모든 카테고리를 가져와 'categories'라는 키에 연결해 담기
        context['no_category_post_count'] = Post.objects.filter(category=None).count
        #카테고리가 지정되지 않은 포스트의 개수를 세어, 'no_category_post_count'에 담기
        return context

class PostList(ListView):  #클래스이름:모델명+리스트
    model = Post
    ordering = '-pk'  # 포스트 최신순
    paginate_by = 5   # 한 페이지에 5개 포스트 보여주기

    def get_context_data(self, *, object_list=None, **kwargs):  #카테고리 카드를 채우기 위한 정보 정의
        context = super(PostList,self).get_context_data()  # 기존에 제공했던 기능을 그대로 가져와 context에 저장
        context['categories'] = Category.objects.all()  # 모든 카테고리를 가져와 'categories'라는 키에 연결해 담기
        context['no_category_post_count'] = Post.objects.filter(category=None).count
        #카테고리가 지정되지 않은 포스트의 개수를 세어, 'no_category_post_count'에 담기
        return context

def category_page(request, slug):  #매개변수로 꼭필요한 request 이외에 slug까지 설정
    if slug == 'no_category' : #만약 매개변수(slug) 값이 'no_category'라면
        category = '미분류'  # category 변수에 실제 Category 모델의 레코드가 아닌, '미분류'문자열 저장
        post_list = Post.objects.filter(category=None)
    else :
        category = Category.objects.get(slug=slug)
        post_list = Post.objects.filter(category=category)
    return render(request, 'blog/post_list.html', {
        'category' : category,
        'post_list' : post_list,
        'categories' : Category.objects.all(),
        'no_category_post_count' : Post.objects.filter(category=None).count
    })

    # 템플릿 필요, 이름: 모델명_list.html : post_list.html <-자동생성
    # 파라미터(자동으로 전달되는 데이터) -> 모델명_list : post_list

class PostSearch(PostList):  # 포스트리스트가 상속 받고있는 ListView도 상속, post_list, post_list.html 자동 호출
    paginate_by = None

    def get_queryset(self):
        q = self.kwargs['q']
        post_list = Post.objects.filter( #필터를 통해 걸러내고 저장
            Q(title__contains=q) | Q(tags__name__contains=q)
        ).distinct()  # 같은 포스트가 여러개 검색되어도 하나만 출력
        return post_list
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search : {q} ({self.get_queryset().count()})'
        return context

class PostDetail(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data() # 기존에 제공했던 기능을 그대로 가져와 context에 저장
        context['categories'] = Category.objects.all()  #모든 카테고리를 가져와 'categories'키에 연결해 담기
        context['no_category_post_count'] = Post.objects.filter(category=None).count #카테고리가 지정되지 않은 개수
        context['comment_form'] = CommentForm
        return context

def tag_page(request, slug):
    tag = Tag.objects.get(slug=slug) #슬러그와 같은 슬러그의 태그를 가져옴
    post_list = tag.post_set.all()  #같은 태그의 모든 포스트를 포스트리스트에 넣기
    return render(request, 'blog/post_list.html', {
        'tag' : tag,  #위의 변수에 저장된 값 전달해서 넘겨주기
        'post_list' : post_list,
        'categories': Category.objects.all(),
        'no_category_post_count': Post.objects.filter(category=None).count
    })

    # 템플릿 모델명_detail.html : post_detail.html
    # 파라미터(자동으로 전달되는 데이터) -> 모델명 : post

def new_comment(request,pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk)
        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()  # 서버에 코멘트 세이브
                return redirect(comment.get_absolute_url())
        else:  # GET
            return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied

class CommentUpdate(UpdateView):
    model = Comment
    form_class = CommentForm
    # CreateView, UpdateView, form을 사용하면
    # 템플릿: 모델명_forms 로 자동 생성  (comment_form)

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate,self).dispatch(request, *args, **kwargs)
        # 가입, 인증되었고 그 포스트의 작성자를 가져와서 현재 작성자와 같은지 확인
        else:
            raise PermissionDenied

#def index(request):
#    posts1 = Post.objects.all().order_by('-pk') # 역순 출력
#    return render (request, 'blog/index.html', {'posts': posts1})

#def single_post_page(request, pk):
#    post2 = Post.objects.get(pk=pk)
#    return render(request, 'blog/single_post_page.html', {'post':post2})

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <title>{% block head_title %}Blog{% endblock %}</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="{% static 'blog/bootstrap4/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" media="screen"></link>
  <script src="https://kit.fontawesome.com/42c02d7b5c.js" crossorigin="anonymous"></script>
</head>
<body>
  {% include 'blog/navbar.html' %}

  <div class="container">
    <div class="row">
      <div class="col-md-8 col-lg-9" id="main-area"> <!-- 메인 에리어 부분만 다름 -->
        {% block main_area %}
        {% endblock %}
      </div>

      <div class="col-md-4 col-lg-3"> <!-- 위에것과 두개 더해서 12 -->
        {% include 'blog/sidebar.html' %}
      </div>
    </div>
  </div>

  {% include 'blog/footer.html' %}

  <!-- <button onclick="whatTimeIsIt()">현재시간</button> -->

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    Edit Comment - Blog
{% endblock %}

{% block main_area %}
  <h1>Edit Comment</h1>
  <hr>
  <form method="post" enctype="multipart/form-data">  <!-- 사용자가 입력한 내용을 전달할 방식: get/post-->
    {% csrf_token %}

      {{form | crispy}} <!--views의 field를 따라 자동 생성(필드명만 만들면 장고가 자동으로) -->

    <button type="submit" class="btn btn-primary float-right">Submit</button>  <!--제출 버튼 추가 -->
  </form>
{% endblock %}

blog/templates/blog/footer.html
    <!-- Footer-->
    <footer class="py-5 bg-dark">
      <div class="container"><p class="m-0 text-center text-white">Copyright &copy; InternetProgramming 2022</p></div>
    </footer>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
</head>
<body>
    <h1>Blog</h1>
    {% for p in posts %}
        <h2> <a href="{{p.get_absolute_url}}"> {{p.title}} </a> </h2>
        <h3> {{p.created_at}} </h3>
        <p> {{p.content}} </p>
    {% endfor %}
</body>
</html>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    {{post.title}} - Blog
{% endblock %}

{% block main_area %}
                    <!-- Post content-->
                    <div id="post-area"> <!-- 포스트 영역 -->
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <h1 class="fw-bolder mb-1">{{post.title | lower}}</h1> <!--데이터 제목-->
                            {% if post.hook_text %}
                            <h5 class="text-muted">{{post.hook_text}}</h5> <!--훅텍스트가 있다면 출력-->
                            {% endif %}
                            <!-- Post meta content / 작성시간 , 작성자명(대문자) 출력 -->
                            <div class="text-muted fst-italic mb-2">
                                Posted on {{post.created_at | date:"Y-m-d h:m:s"}} by {{post.author | upper}}</div>
                            <!-- Post categories-->
                            {% if post.category %}
                                <a class="badge bg-secondary text-decoration-none link-light"
                                   href="{{post.category.get_absolute_url}}">
                                    {{post.category}}</a>
                            {% else %}
                                <a class="badge bg-secondary text-decoration-none link-light"
                                   href="/blog/category/no_category/">
                                    미분류</a>
                            {% endif %}
                        </header>
                        {% if user.is_authenticated and user == post.author %}
                            <a href="/blog/update_post/{{post.pk}}/" role="button"
                                class="btn btn-info btn-sm float-right">
                                <i class="fas fa-pen"></i> Edit Post </a>
                        {% endif %}
                        <!-- Preview image figure-->
                        <figure class="mb-4">
                            {% if post.head_image %} <!--이미지가 있다면 출력 -->
                            <img class="img-fluid rounded" src="{{post.head_image.url}}" alt="{{p.title}}의 head_image" />
                            {% else %}
                            <img class="img-fluid rounded" src="https://picsum.photos/seed/{{post.pk}}/800/200" alt="random image" />
                            <!-- 시드값으로 해당 프라이머리 키를 넣으면 랜덤이 아닌 고정 -->
                            {% endif %}
                        </figure>
                        <!-- Post content-->
                        <section class="mb-5">
                            <p class="fs-5 mb-4">{{post.content}}</p>
                            {% if post.tags.exists %}   <!--exists함수 사용해야 있는지 확인 가능 -->
                                <i class="fas fa-tag"></i>  <!-- 태그 아이콘 사용-->
                                {% for t in post.tags.iterator %} <!-- iterator 있어야 for문으로 돌리기 가능 -->
                                    <span class="badge badge-pill badge-light"> <!--뱃지 형태로 출력-->
                                        <a href="{{t.get_absolute_url}}">{{t}}</a>
                                    </span>
                                {% endfor %}
                                <br><br>
                            {% endif %}
                            {% if post.file_upload %}
                            <a href="{{post.file_upload.url}}" class="btn btn-outline-dark" role="button" download>
                                {% if post.get_file_ext == 'xlsx' or post.get_file_ext == 'xls' %}
                                <i class="fa-regular fa-file-excel"></i>
                                {% elif post.get_file_ext == 'docx' or post.get_file_ext == 'doc' %}
                                <i class="fa-duotone fa-file-word"></i>
                                {% else %}
                                <i class="fa-regular fa-file"></i>
                                {% endif %}
                                Download {{post.get_file_name}}
                            </a>
                            {% endif %}
                        </section>
                    </div>
                    <!-- Comments section-->
                    <div id="comment-area" class="mb-5"> <!-- 댓글 영역 -->
                        <div class="card bg-light">
                            <div class="card-body">
                                <!-- Comment form-->
                                {% if user.is_authenticated %}
                                <form class="mb-4" id="comment-form" method="post"
                                    action="{{post.get_absolute_url}}new_comment/"> <!-- submit이 클릭되면 액션 실행-->
                                    {% csrf_token %}
                                    <div class="form-group">
                                        {{comment_form | crispy}}
                                    </div>
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </form>
                                {% else %}
                                <a role="button" class="btn btn-dark btn-block btn-sm" href="#" data-toggle="modal" data-target="#loginModal">
                                    Log in and Leave a comment
                                </a>
                                {% endif %}
                                {% if post.comment_set.exists %}  <!-- 해당하는(커멘트가 있는) 포스트 가져오기 -->
                                {% for comment in post.comment_set.iterator %}
                                <!-- Single comment-->
                                <div class="media d-flex" id="comment-{{comment.pk}}">
                                    <img class="mr-3 rounded-circle" src="{{comment.get_avatar_url}}" alt="{{comment.author}}" width="60px"/>
                                    <div class="media-body ms-3">
                                        {% if user.is_authenticated and comment.author == user %}
                                            <a role="button" class="btn btn-sm btn-info float-right"
                                               href="/blog/update_comment/{{comment.pk}}">
                                                Edit
                                            </a>
                                        {% endif %}
                                        <div class="fw-bold">
                                            {{comment.author.username}}
                                            <small class="text-muted">{{comment.created_at}}</small>
                                        </div>
                                        <p>{{comment.content | linebreaks}}</p>
                                        {% if comment.created_at != comment.modified_at %}
                                            <p class="text-muted float-right">
                                                <small>Updated : {{comment.modified_at}}</small>
                                            </p>
                                        {% endif %}
                                    </div>
                                </div>
                                {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    Create Post - Blog
{% endblock %}

{% block main_area %}
  <h1>Create New Post</h1>
  <hr>
  <form method="post" enctype="multipart/form-data">  <!-- 사용자가 입력한 내용을 전달할 방식: get/post-->
    {% csrf_token %}

      {{form | crispy}} <!--views의 field를 따라 자동 생성(필드명만 만들면 장고가 자동으로) -->
      <div id="div_id_tags_str">
        <label for="id_tags">Tags:</label>
        <input type="text" id="id_tags" name="tags_str"
          class="textinput textInput form-control">
      </div>

    <button type="submit" class="btn btn-primary float-right">Submit</button>  <!--제출 버튼 추가 -->
  </form>
{% endblock %}

blog/templates/blog/post_update_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    Update Post - Blog
{% endblock %}

{% block main_area %}
  <h1>Update Post</h1>
  <hr>
  <form method="post" enctype="multipart/form-data">  <!-- 사용자가 입력한 내용을 전달할 방식: get/post-->
    {% csrf_token %}

      {{form | crispy}} <!--views의 field를 따라 자동 생성(필드명만 만들면 장고가 자동으로) -->
      <div id="div_id_tags_str">
        <label for="id_tags">Tags:</label>
        <input type="text" id="id_tags" name="tags_str" value="{{tags_str_default}}"
        class="textinput textInput form-control">
      </div>

    <button type="submit" class="btn btn-primary float-right">Submit</button>  <!--제출 버튼 추가 -->
  </form>
{% endblock %}

blog/templates/blog/single_post_page.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>{{ post.title }}</title>
</head>
<body>
  <h1>{{post.title}}</h1>
  <h3>{{post.created_at}}</h3>
  <p>{{post.content}}</p>

  <hr />
  <h4>여기에 댓글</h4>

</body>
</html>